/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoGrupal;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gerson
 */
public class InventariodeTienda extends javax.swing.JFrame {

    /**
     * Creates new form InventariodeTienda
     */
    public InventariodeTienda() {
        initComponents();
        this.tabladetalle.setModel(modelo);
        this.modelo.addColumn("NACIONALIDAD");
        this.modelo.addColumn("GENERO");
        this.modelo.addColumn("TALLAS");
        this.modelo.addColumn("PRENDAS");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("PRECIO UNITARIO");
        this.modelo.addColumn("Total A PAGAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbonacionalidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnhombre = new javax.swing.JRadioButton();
        btnmujer = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cbotallas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtprenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnfacturar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalle = new javax.swing.JTable();
        btnlimpiartabla = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        btnnetoapagar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtnetoapagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                                                                                                                   Inventario de Tienda de Ropa");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar Compra"));

        jLabel2.setText("Nacionalidad");

        cbonacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Hondureño", "Extranjero", " ", " " }));

        jLabel3.setText("Genero:");

        buttonGroup1.add(btnhombre);
        btnhombre.setText("Hombre");

        buttonGroup1.add(btnmujer);
        btnmujer.setText("Mujer");

        jLabel4.setText("Tallas:");

        cbotallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "S", "M", "L", "XL" }));

        jLabel5.setText("Prenda");

        txtprenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprendaActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad");

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });

        jLabel7.setText("   Precio");

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        jLabel8.setText("Total a Pagar");

        btnfacturar.setText("Facturar Compra");
        btnfacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnmujer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnhombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnfacturar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhombre)
                    .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmujer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfacturar)
                    .addComponent(btneliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de la Compra"));

        tabladetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladetalle);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnlimpiartabla.setText("Limpiar Tabla");
        btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablaActionPerformed(evt);
            }
        });

        btnquitar.setText("Quitar Compra");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        btnnetoapagar.setText("Neto a Pagar");
        btnnetoapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetoapagarActionPerformed(evt);
            }
        });

        jLabel9.setText("Neto a Pagar S/.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnlimpiartabla)
                                .addGap(18, 18, 18)
                                .addComponent(btnquitar)
                                .addGap(18, 18, 18)
                                .addComponent(btnnetoapagar)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(txtnetoapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiartabla)
                    .addComponent(btnquitar)
                    .addComponent(btnnetoapagar)
                    .addComponent(jLabel9)
                    .addComponent(txtnetoapagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel modelo=new DefaultTableModel();
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        this.cbonacionalidad.setSelectedIndex(0);
        if(btnhombre.isSelected()){
            
        }
        if(btnmujer.isSelected()){
            
        }
        this.cbotallas.setSelectedIndex(0);
        this.txtprenda.setText("");
        this.txtcantidad.setText("");
        this.txtprecio.setText("");
        this.txttotal.setText("");
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnfacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturarActionPerformed
        // TODO add your handling code here:
        descuentos_hombres_hondureño();
        descuentos_mujeres_hondureña();
        descuentos_hombres_extranjero();
        descuentos_mujeres_extranjera();
        
        if(btnhombre.isSelected()){
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedIndex(),"Hombre",
                this.cbotallas.getSelectedItem(),this.txtprenda.getText(),this.txtcantidad.getText(),
                this.txtprecio.getText(),this.txttotal.getText()});
            
        }
        else if (btnmujer.isSelected()){
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedIndex(),"Mujer",
                this.cbotallas.getSelectedItem(),this.txtprenda.getText(),this.txtcantidad.getText(),
                this.txtprecio.getText(),this.txttotal.getText()});
        }
    }//GEN-LAST:event_btnfacturarActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        // TODO add your handling code here:
        modelo.removeRow(this.tabladetalle.getSelectedRow());
    }//GEN-LAST:event_btnquitarActionPerformed

    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        // TODO add your handling code here:
        int x=this.modelo.getRowCount();
        for (int y = 0; y <=x;  y++) {
        this.modelo.removeRow(0);
    }
        this.txtnetoapagar.setText("");
    }//GEN-LAST:event_btnlimpiartablaActionPerformed

    private void btnnetoapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetoapagarActionPerformed
        // TODO add your handling code here:
        double sumatoria;
        double sumatorial=0;
        int totalrow=tabladetalle.getRowCount();
        totalrow-=1;
        for (int i = 0; i <= (totalrow); i++){
            sumatoria=Double.parseDouble(String.valueOf(tabladetalle.getValueAt(i, 6)));
            sumatorial+=sumatoria;
        }
        txtnetoapagar.setText("S."+String.valueOf(sumatorial));
                
    }//GEN-LAST:event_btnnetoapagarActionPerformed

    private void txtprendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprendaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtprendaActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcantidadActionPerformed
public void descuentos_hombres_hondureño(){
        double cantidad_s,precio_s,total_s,descuentos_s=0.04;
        double cantidad_m,precio_m,total_m,descuentos_m=0.06;
        double cantidad_l,precio_l,total_l,descuentos_l=0.03;
        
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.btnhombre.isSelected()){
                if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*descuentos_s);
                this.txttotal.setText(String.valueOf(total_s));
                
               }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.btnhombre.isSelected()){
                if(cbotallas.getSelectedIndex()==2){
                   cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*descuentos_m);
                this.txttotal.setText(String.valueOf(total_m)); 
                }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.btnhombre.isSelected()){
                if(cbotallas.getSelectedIndex()==3){
                   cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*descuentos_l);
                this.txttotal.setText(String.valueOf(total_l)); 
                }
            }
        }
        
    }
    public void descuentos_mujeres_hondureña(){
        double cantidad_s,precio_s,total_s,descuentos_s=0.08;
        double cantidad_m,precio_m,total_m,descuentos_m=0.06;
        double cantidad_l,precio_l,total_l,descuentos_l=0.10;
        
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.btnmujer.isSelected()){
                if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*descuentos_s);
                this.txttotal.setText(String.valueOf(total_s));
                
            }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.btnmujer.isSelected()){
                if(cbotallas.getSelectedIndex()==2){
                   cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*descuentos_m);
                this.txttotal.setText(String.valueOf(total_m)); 
                }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.btnmujer.isSelected()){
                if(cbotallas.getSelectedIndex()==3){
                   cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*descuentos_l);
                this.txttotal.setText(String.valueOf(total_l)); 
                }
            }
        }
        
    }
    public void descuentos_hombres_extranjero(){
        double cantidad_s,precio_s,total_s,descuentos_s=0.04;
        double cantidad_m,precio_m,total_m,descuentos_m=0.06;
        double cantidad_l,precio_l,total_l,descuentos_l=0.10;
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.btnhombre.isSelected()){
                if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*descuentos_s);
                this.txttotal.setText(String.valueOf(total_s));
                
            }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.btnhombre.isSelected()){
                if(cbotallas.getSelectedIndex()==2){
                   cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*descuentos_m);
                this.txttotal.setText(String.valueOf(total_m)); 
                }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.btnhombre.isSelected()){
                if(cbotallas.getSelectedIndex()==3){
                   cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*descuentos_l);
                this.txttotal.setText(String.valueOf(total_l)); 
                }
            }
        }
        
    }
    public void descuentos_mujeres_extranjera(){
        double cantidad_s,precio_s,total_s,descuentos_s=0.07;
        double cantidad_m,precio_m,total_m,descuentos_m=0.05;
        double cantidad_l,precio_l,total_l,descuentos_l=0.10;
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.btnmujer.isSelected()){
                if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*descuentos_s);
                this.txttotal.setText(String.valueOf(total_s));
                
            }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.btnmujer.isSelected()){
                if(cbotallas.getSelectedIndex()==2){
                   cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*descuentos_m);
                this.txttotal.setText(String.valueOf(total_m)); 
                }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.btnmujer.isSelected()){
                if(cbotallas.getSelectedIndex()==3){
                   cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*descuentos_l);
                this.txttotal.setText(String.valueOf(total_l)); 
                }
            }
        }
        
    }
    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtprecioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventariodeTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventariodeTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventariodeTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventariodeTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventariodeTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnfacturar;
    private javax.swing.JRadioButton btnhombre;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JRadioButton btnmujer;
    private javax.swing.JButton btnnetoapagar;
    private javax.swing.JButton btnquitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbonacionalidad;
    private javax.swing.JComboBox<String> cbotallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladetalle;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnetoapagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprenda;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
